export const SEARCH_LEGAL_DEFINITION = 'SEARCH_LEGAL_DEFINITION';
export const CLEAR_RESULTS = 'CLEAR_RESULTS';
export const SET_LOADING = 'SET_LOADING';
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';
